# Generated by Django 5.0.6 on 2024-06-27 10:36

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_chat', '0002_chatgroup_admin_chatgroup_groupchat_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=120, unique=True, verbose_name='Nombre del grupo'),
        ),
    ]
